LARGURA = 960          
ALTURA = 520          
FPS = 60              
TAMANHO_BLOCO = 40     

VIDAS_INICIAIS = 3         
PONTOS_CRISTAL = 20        
TEMPO_INVENCIVEL = 1000    
GOLPES_PARA_VENCER = 5
VELOCIDADE_INICIAL = 1.3   
VELOCIDADE_MAXIMA = 1.9    
VELOCIDADE_CHEFE = 1.3    
FASE_CHEFE_ATIVA = False  
